-- hsqldb
--
CREATE TABLE IMAGE_GALLERY_IMAGE_T (
	ID bigint generated by default as identity (start with 1),
	CONTEXT varchar(255) not null,
	TITLE varchar(255) default '' not null,
	FILE_ID varchar(255),
	DESCRIPTION longvarchar,
	primary key (ID)
);
